name: Build official Chia Docker Image

on:
  workflow_dispatch:
    inputs:
      upstream_branch:
        description: 'chia branch name to use'
        required: true
        default: 'dev'
      image_tag:
        description: 'special tag for this image build'
        required: true
        default: 'unstable'

jobs:
  docker_build_and_publish_github:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGE_ADMIN_PAT }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build docker image and push to github packages
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          no-cache: true
          push: true
          build-args: |
            "BRANCH=${{ github.event.inputs.upstream_branch }}"
          tags: |
            ghcr.io/chia-network/chia:${{ github.event.inputs.image_tag }}
            chianetwork/chia-docker:${{ github.event.inputs.image_tag }}
