name: Build Main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker_build_and_publish_github:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGE_ADMIN_PAT }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      # Get the most recent release from chia-blockchain and build that
      - uses: actions/github-script@v4
        id: 'latest-tag'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const releases = await github.repos.listReleases({
              owner: 'Chia-Network',
              repo: 'chia-blockchain',
            });
            return releases.data[0].tag_name;

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/chia-network/chia
            chianetwork/chia-docker
          tags: |
            type=raw,value=latest
            type=raw,value=${{ steps.latest-tag.outputs.result }}

      - name: Build docker image and push to github packages
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          no-cache: true
          push: true
          build-args: |
            "BRANCH=${{ steps.latest-tag.outputs.result }}"
          tags: ${{ steps.meta.outputs.tags }}
