#!/usr/bin/with-contenv bash

# update chia-blockchain
chown root:root -R /config /chia-blockchain
cd /chia-blockchain
git fetch
git checkout latest
git reset --hard FETCH_HEAD
/bin/sh install.sh
chown abc:abc -R /config /chia-blockchain

# activate chia-blockchain venv
. ./activate

# init certs
s6-setuidgid abc /chia-blockchain/venv/bin/chia init
if [[ -n "${CACERTS_DIR}" ]]
then
  echo "**** re-init with provided cacerts ****"
  s6-setuidgid abc /chia-blockchain/venv/bin/chia init -c ${CACERTS_DIR}
fi

# generate keys
if [[ -f /config/chia-mnemonic.txt ]]
then
  echo "**** Previous keys found ****"
  KEYS="/config/chia-mnemonic.txt"
fi

if [[ ${KEYS} == "generate" ]]
then
  echo "**** Generating new keys ****"
  s6-setuidgid abc chia keys generate | tee /config/key-tmp.txt
  sed -n '3p' /config/key-tmp.txt | tee /config/chia-mnemonic.txt &>/dev/null
  rm -f /config/key-tmp.txt
else
  echo "**** Installing existing keys ****"
  s6-setuidgid abc chia keys add -f ${KEYS}
  if [[ ! -f /config/chia-mnemonic.txt ]]
  then
    cat ${KEYS} | tee /config/chia-mnemonic.txt &>/dev/null
  fi
fi

# configure plots directory
if [[ ! "$(ls -A ${PLOTS_DIR})" ]]
then
  echo "Plots directory appears to be empty and you have not specified another, try mounting a plot directory with the docker -v command"
fi

s6-setuidgid abc chia plots add -d ${PLOTS_DIR}

# configure chia daemon
s6-setuidgid abc chia configure --set-log-level INFO
s6-setuidgid abc chia configure --upnp false

# configure harvester settings
if [[ ${HARVESTER} == 'true' ]]
then
  if [[ -z ${FARMER_ADDRESS} || -z ${FARMER_PORT} ]]
  then
    echo "A farmer peer address and port are required."
    exit
  else
    s6-setuidgid abc chia configure --set-farmer-peer ${FARMER_ADDRESS}:${FARMER_PORT}
  fi
fi

# configured testnet
if [[ ${TESTNET} == "true" ]]
then
  if [[ -z $FULL_NODE_PORT || $FULL_NODE_PORT == "null" ]]
  then
    s6-setuidgid abc chia configure --set-fullnode-port 58444
  else
    s6-setuidgid abc chia configure --set-fullnode-port ${FULL_NODE_PORT}
  fi
fi

# remove ipv6
sed -i 's/localhost/127.0.0.1/g' /config/.chia/mainnet/config/config.yaml

# deactivate chia-blockchain venv
deactivate

# set proper user permissions
chown abc:abc -R \
  /config /chia-blockchain
